# Generated by Django 4.2.29 on 2026-03-20 17:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('keyword', 'Keyword'), ('action', 'Action'), ('ability_word', 'Ability Word'), ('misc', 'Miscellaneous Ability')], db_index=True, default='keyword', max_length=20)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'mechanic',
                'verbose_name_plural': 'mechanics',
                'ordering': ['kind', 'name'],
            },
        ),
        migrations.AddField(
            model_name='creaturetype',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='creaturetype',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
