# Generated by Django 4.2.29 on 2026-05-03 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tolarian', '0008_collectionitem_acquired_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeckEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('commander', models.CharField(blank=True, max_length=200)),
                ('decklist_text', models.TextField(blank=True, help_text='Snapshot of the decklist evaluated.')),
                ('bracket', models.CharField(blank=True, choices=[('1', '1 — Exhibition'), ('2', '2 — Core'), ('3', '3 — Upgraded'), ('4', '4 — Optimized'), ('5', '5 — cEDH')], help_text='AI-suggested bracket tier.', max_length=2)),
                ('bracket_user', models.CharField(blank=True, choices=[('1', '1 — Exhibition'), ('2', '2 — Core'), ('3', '3 — Upgraded'), ('4', '4 — Optimized'), ('5', '5 — cEDH')], help_text="Owner's self-rated bracket tier.", max_length=2)),
                ('honest_scores', models.JSONField(blank=True, default=dict)),
                ('narrative', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('error', models.TextField(blank=True)),
                ('prompt', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to='tolarian.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'deck evaluation',
                'verbose_name_plural': 'deck evaluations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='conflux_dec_user_id_35aa68_idx'), models.Index(fields=['deck', '-created_at'], name='conflux_dec_deck_id_d68e99_idx')],
            },
        ),
    ]
