# Generated by Django 4.2.29 on 2026-05-03 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conflux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckevaluation',
            name='card_tags',
            field=models.JSONField(blank=True, default=list, help_text='[{name, tags: [...]}, ...] from the preprocessing step.'),
        ),
        migrations.AddField(
            model_name='deckevaluation',
            name='combos',
            field=models.JSONField(blank=True, default=list, help_text='[{pieces, type, interactable, resilient}, ...]'),
        ),
        migrations.AddField(
            model_name='deckevaluation',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weighted final score 0.00–10.00, computed in Python from honest_scores.', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='deckevaluation',
            name='honest_tier',
            field=models.CharField(blank=True, choices=[('jank', 'Jank'), ('casual', 'Casual'), ('mid', 'Mid Power'), ('high', 'High Power'), ('cedh', 'cEDH')], max_length=10),
        ),
        migrations.AddField(
            model_name='deckevaluation',
            name='intent_label',
            field=models.CharField(blank=True, choices=[('competitive', 'Competitive'), ('optimized', 'Optimized'), ('casual', 'Casual'), ('jank', 'Jank / Meme')], max_length=20),
        ),
        migrations.AddField(
            model_name='deckevaluation',
            name='intent_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='deckevaluation',
            name='bracket',
            field=models.CharField(blank=True, choices=[('1', '1 — Exhibition'), ('2', '2 — Core'), ('3', '3 — Upgraded'), ('4', '4 — Optimized'), ('5', '5 — cEDH')], max_length=2),
        ),
        migrations.AlterField(
            model_name='deckevaluation',
            name='honest_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Per-axis scores returned by the LLM.'),
        ),
    ]
