# Generated by Django 4.2.29 on 2026-05-03 03:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0007_alter_cardprint_frame_effects_and_more'),
        ('conflux', '0002_deckevaluation_card_tags_deckevaluation_combos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('function_tags', models.JSONField(blank=True, default=list)),
                ('theme_tags', models.JSONField(blank=True, default=list)),
                ('reasoning', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('vocabulary_version', models.PositiveSmallIntegerField(default=1)),
                ('error', models.TextField(blank=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conflux_tags', to='multiverse.card')),
            ],
            options={
                'verbose_name': 'card tag',
                'verbose_name_plural': 'card tags',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['model_name', 'vocabulary_version'], name='conflux_car_model_n_38fefe_idx')],
            },
        ),
    ]
