# Generated by Django 4.2.29 on 2026-03-31 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tolarian', '0007_deck_share_token_deckversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('format', models.CharField(choices=[('standard', 'Standard'), ('pioneer', 'Pioneer'), ('modern', 'Modern'), ('legacy', 'Legacy'), ('vintage', 'Vintage'), ('commander', 'Commander'), ('pauper', 'Pauper'), ('draft', 'Draft'), ('sealed', 'Sealed'), ('oathbreaker', 'Oathbreaker'), ('brawl', 'Brawl'), ('other', 'Other')], default='commander', max_length=20)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=4)),
                ('opponent_name', models.CharField(blank=True, help_text='Nombre del oponente (texto libre).', max_length=100)),
                ('opponent_deck_name', models.CharField(blank=True, help_text='Nombre o arquetipo del deck oponente.', max_length=100)),
                ('turns', models.PositiveSmallIntegerField(blank=True, help_text='Número de turnos de la partida.', null=True)),
                ('date_played', models.DateField(help_text='Fecha en que se jugó la partida.')),
                ('notes', models.TextField(blank=True)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_records', to='tolarian.deck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'game record',
                'verbose_name_plural': 'game records',
                'ordering': ['-date_played', '-created_at'],
            },
        ),
    ]
