# Generated by Django 4.2.29 on 2026-03-31 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tolarian', '0007_deck_share_token_deckversion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phyrexian', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('format', models.CharField(choices=[('standard', 'Standard'), ('pioneer', 'Pioneer'), ('modern', 'Modern'), ('legacy', 'Legacy'), ('vintage', 'Vintage'), ('commander', 'Commander'), ('pauper', 'Pauper'), ('draft', 'Draft'), ('sealed', 'Sealed'), ('oathbreaker', 'Oathbreaker'), ('brawl', 'Brawl'), ('other', 'Other')], default='commander', max_length=20)),
                ('starting_life', models.PositiveSmallIntegerField(default=40)),
                ('status', models.CharField(choices=[('active', 'Active'), ('finished', 'Finished')], default='active', max_length=10)),
                ('current_turn', models.PositiveSmallIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'game session',
                'verbose_name_plural': 'game sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('life', models.IntegerField(default=40)),
                ('poison', models.PositiveSmallIntegerField(default=0)),
                ('energy', models.PositiveSmallIntegerField(default=0)),
                ('experience', models.PositiveSmallIntegerField(default=0)),
                ('commander_damage', models.JSONField(blank=True, default=dict)),
                ('is_monarch', models.BooleanField(default=False)),
                ('has_initiative', models.BooleanField(default=False)),
                ('has_citys_blessing', models.BooleanField(default=False)),
                ('color', models.CharField(default='#6366F1', help_text='Hex color for player panel.', max_length=7)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tolarian.deck')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='phyrexian.gamesession')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'player slot',
                'verbose_name_plural': 'player slots',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='LifeChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('delta', models.IntegerField(help_text='Positive = gain, negative = loss.')),
                ('life_after', models.IntegerField()),
                ('turn', models.PositiveSmallIntegerField(default=1)),
                ('source', models.CharField(blank=True, help_text='What caused the change (combat, spell, etc.).', max_length=50)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_changes', to='phyrexian.playerslot')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='life_changes', to='phyrexian.gamesession')),
            ],
            options={
                'verbose_name': 'life change',
                'verbose_name_plural': 'life changes',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='phyrexian.playerslot'),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_records', to='phyrexian.gamesession'),
        ),
        migrations.AddConstraint(
            model_name='playerslot',
            constraint=models.UniqueConstraint(fields=('session', 'position'), name='unique_session_position'),
        ),
    ]
