# Generated by Django 4.2.29 on 2026-03-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyrexian', '0002_gamesession_playerslot_lifechange_gamesession_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerslot',
            name='background_image',
            field=models.URLField(blank=True, help_text='Card art URL for player panel background.'),
        ),
        migrations.AddField(
            model_name='playerslot',
            name='commander_tax',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerslot',
            name='is_day',
            field=models.BooleanField(default=True, help_text='Day/Night cycle: True=Day, False=Night'),
        ),
        migrations.AddField(
            model_name='playerslot',
            name='rad',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerslot',
            name='storm_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerslot',
            name='treasure',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
