# Generated by Django 4.2.29 on 2026-04-12 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyrexian', '0003_playerslot_background_image_playerslot_commander_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerslot',
            name='placement',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
