# Generated by Django 4.2.29 on 2026-04-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyrexian', '0004_add_placement_to_playerslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerslot',
            name='speed',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerslot',
            name='the_ring',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
