# Generated by Django 4.2.29 on 2026-04-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyrexian', '0005_add_speed_and_the_ring'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerslot',
            name='commander_taxes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
