# Generated by Django 4.2.29 on 2026-04-14 19:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tolarian', '0007_deck_share_token_deckversion_and_more'),
        ('phyrexian', '0007_playerslot_commanders'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerecord',
            name='elimination_cause',
            field=models.CharField(blank=True, choices=[('life', 'Life (0 or less)'), ('poison', 'Poison Counters'), ('commander_damage', 'Commander Damage'), ('alt_wincon', 'Alt. Win Condition'), ('direct', 'Direct Elimination')], help_text='How the user was eliminated (if applicable).', max_length=20),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='my_commanders',
            field=models.JSONField(blank=True, default=list, help_text="Commander name(s) for user's deck."),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='my_placement',
            field=models.PositiveSmallIntegerField(default=0, help_text="User's finishing position (1 = winner)."),
        ),
        migrations.AddField(
            model_name='playerslot',
            name='elimination_cause',
            field=models.CharField(blank=True, choices=[('life', 'Life (0 or less)'), ('poison', 'Poison Counters'), ('commander_damage', 'Commander Damage'), ('alt_wincon', 'Alt. Win Condition'), ('direct', 'Direct Elimination')], max_length=20),
        ),
        migrations.CreateModel(
            name='GamePlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('deck_name', models.CharField(blank=True, help_text='Deck name or archetype (free text).', max_length=100)),
                ('commanders', models.JSONField(blank=True, default=list, help_text='Commander name(s).')),
                ('placement', models.PositiveSmallIntegerField(default=0, help_text='Finishing position (1 = winner).')),
                ('elimination_cause', models.CharField(blank=True, choices=[('life', 'Life (0 or less)'), ('poison', 'Poison Counters'), ('commander_damage', 'Commander Damage'), ('alt_wincon', 'Alt. Win Condition'), ('direct', 'Direct Elimination')], max_length=20)),
                ('is_winner', models.BooleanField(default=False)),
                ('deck', models.ForeignKey(blank=True, help_text='Link to a deck on the site (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tolarian.deck')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponents', to='phyrexian.gamerecord')),
            ],
            options={
                'verbose_name': 'game player',
                'verbose_name_plural': 'game players',
                'ordering': ['placement', 'created_at'],
            },
        ),
    ]
