# Generated by Django 4.2.29 on 2026-04-14 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyrexian', '0008_add_elimination_tracking_and_game_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='elimination_cause',
            field=models.CharField(blank=True, choices=[('life', 'Life (0 or less)'), ('poison', 'Poison Counters'), ('commander_damage', 'Commander Damage'), ('alt_wincon', 'Alt. Win Condition'), ('forfeit', 'Forfeit'), ('alt_losecon', 'Alt. Lose Condition')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gamerecord',
            name='elimination_cause',
            field=models.CharField(blank=True, choices=[('life', 'Life (0 or less)'), ('poison', 'Poison Counters'), ('commander_damage', 'Commander Damage'), ('alt_wincon', 'Alt. Win Condition'), ('forfeit', 'Forfeit'), ('alt_losecon', 'Alt. Lose Condition')], help_text='How the user was eliminated (if applicable).', max_length=20),
        ),
        migrations.AlterField(
            model_name='playerslot',
            name='elimination_cause',
            field=models.CharField(blank=True, choices=[('life', 'Life (0 or less)'), ('poison', 'Poison Counters'), ('commander_damage', 'Commander Damage'), ('alt_wincon', 'Alt. Win Condition'), ('forfeit', 'Forfeit'), ('alt_losecon', 'Alt. Lose Condition')], max_length=20),
        ),
    ]
