# Generated by Django 4.2.29 on 2026-04-16 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phyrexian', '0009_update_elimination_cause_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='elimination_turn',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Turn number when this opponent was eliminated.', null=True),
        ),
        migrations.AddField(
            model_name='gameplayer',
            name='eliminator_name',
            field=models.CharField(blank=True, help_text='Name of the player who eliminated this opponent (own name = forfeit).', max_length=100),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='elimination_turn',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Turn number when the user was eliminated.', null=True),
        ),
        migrations.AddField(
            model_name='gamerecord',
            name='eliminator_name',
            field=models.CharField(blank=True, help_text='Name of the player who eliminated the user (own name = forfeit).', max_length=100),
        ),
        migrations.AddField(
            model_name='playerslot',
            name='elimination_turn',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Turn number when this player was eliminated.', null=True),
        ),
        migrations.AddField(
            model_name='playerslot',
            name='eliminator',
            field=models.ForeignKey(blank=True, help_text='Player slot that eliminated this one (self = forfeit).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eliminations', to='phyrexian.playerslot'),
        ),
    ]
