# Generated by Django 4.2.29 on 2026-04-16 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tolarian', '0007_deck_share_token_deckversion_and_more'),
        ('phyrexian', '0010_add_elimination_turn_and_eliminator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('format', models.CharField(choices=[('standard', 'Standard'), ('pioneer', 'Pioneer'), ('modern', 'Modern'), ('legacy', 'Legacy'), ('vintage', 'Vintage'), ('commander', 'Commander'), ('pauper', 'Pauper'), ('draft', 'Draft'), ('sealed', 'Sealed'), ('oathbreaker', 'Oathbreaker'), ('brawl', 'Brawl'), ('other', 'Other')], default='commander', max_length=20)),
                ('bracket_type', models.CharField(choices=[('single_elim', 'Single Elimination'), ('swiss', 'Swiss')], default='swiss', max_length=20)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('active', 'Active'), ('finished', 'Finished')], default='setup', max_length=10)),
                ('pod_size', models.PositiveSmallIntegerField(default=4, help_text='Players per table (2 for 1v1, 3-4 for multiplayer).')),
                ('swiss_rounds', models.PositiveSmallIntegerField(blank=True, help_text='Number of Swiss rounds (auto-calculated if blank).', null=True)),
                ('current_round', models.PositiveSmallIntegerField(default=0)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_tournaments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TournamentMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('table_number', models.PositiveSmallIntegerField(default=1)),
                ('bracket_position', models.PositiveSmallIntegerField(default=0, help_text='Position in single-elim bracket.')),
                ('is_complete', models.BooleanField(default=False)),
                ('is_bye', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['table_number'],
            },
        ),
        migrations.CreateModel(
            name='TournamentRound',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('round_number', models.PositiveSmallIntegerField()),
                ('is_complete', models.BooleanField(default=False)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='phyrexian.tournament')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='TournamentParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('deck_name', models.CharField(blank=True, max_length=100)),
                ('commanders', models.JSONField(blank=True, default=list)),
                ('seed', models.PositiveSmallIntegerField(default=0)),
                ('match_points', models.PositiveSmallIntegerField(default=0)),
                ('match_wins', models.PositiveSmallIntegerField(default=0)),
                ('match_losses', models.PositiveSmallIntegerField(default=0)),
                ('match_draws', models.PositiveSmallIntegerField(default=0)),
                ('game_win_pct', models.FloatField(default=0.0)),
                ('opp_match_win_pct', models.FloatField(default=0.0)),
                ('opp_game_win_pct', models.FloatField(default=0.0)),
                ('dropped', models.BooleanField(default=False)),
                ('final_standing', models.PositiveSmallIntegerField(default=0)),
                ('deck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='tolarian.deck')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='phyrexian.tournament')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-match_points', '-opp_match_win_pct', '-game_win_pct', 'seed'],
            },
        ),
        migrations.CreateModel(
            name='TournamentMatchPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('result', models.CharField(blank=True, choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw')], max_length=4)),
                ('placement', models.PositiveSmallIntegerField(default=0, help_text='1=winner in this match.')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='phyrexian.tournamentmatch')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_entries', to='phyrexian.tournamentparticipant')),
            ],
            options={
                'ordering': ['placement'],
            },
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='phyrexian.tournamentround'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_matches', to='phyrexian.gamesession'),
        ),
        migrations.CreateModel(
            name='EloRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('format', models.CharField(choices=[('standard', 'Standard'), ('pioneer', 'Pioneer'), ('modern', 'Modern'), ('legacy', 'Legacy'), ('vintage', 'Vintage'), ('commander', 'Commander'), ('pauper', 'Pauper'), ('draft', 'Draft'), ('sealed', 'Sealed'), ('oathbreaker', 'Oathbreaker'), ('brawl', 'Brawl'), ('other', 'Other')], max_length=20)),
                ('rating', models.IntegerField(default=1200)),
                ('matches_played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('peak_rating', models.IntegerField(default=1200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='EloHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('format', models.CharField(choices=[('standard', 'Standard'), ('pioneer', 'Pioneer'), ('modern', 'Modern'), ('legacy', 'Legacy'), ('vintage', 'Vintage'), ('commander', 'Commander'), ('pauper', 'Pauper'), ('draft', 'Draft'), ('sealed', 'Sealed'), ('oathbreaker', 'Oathbreaker'), ('brawl', 'Brawl'), ('other', 'Other')], max_length=20)),
                ('old_rating', models.IntegerField()),
                ('new_rating', models.IntegerField()),
                ('change', models.IntegerField()),
                ('opponents_snapshot', models.JSONField(blank=True, default=list, help_text='[{"name": "...", "rating": N, "placement": N}, ...]')),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elo_changes', to='phyrexian.gamerecord')),
                ('tournament_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elo_changes', to='phyrexian.tournamentmatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elo_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tournamentround',
            constraint=models.UniqueConstraint(fields=('tournament', 'round_number'), name='unique_tournament_round'),
        ),
        migrations.AddConstraint(
            model_name='tournamentparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('tournament', 'user'), name='unique_tournament_user'),
        ),
        migrations.AddConstraint(
            model_name='tournamentmatchplayer',
            constraint=models.UniqueConstraint(fields=('match', 'participant'), name='unique_match_participant'),
        ),
        migrations.AddConstraint(
            model_name='elorating',
            constraint=models.UniqueConstraint(fields=('user', 'format'), name='unique_user_format_elo'),
        ),
    ]
