# Generated by Django 4.2.29 on 2026-04-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phyrexian', '0011_add_tournament_and_elo_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='best_of',
            field=models.PositiveSmallIntegerField(default=1, help_text='Best-of-N games per match (1 = single game, 3 = Bo3).'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='current_game',
            field=models.PositiveSmallIntegerField(default=1, help_text='Current game number in a best-of-N match.'),
        ),
        migrations.AddField(
            model_name='tournamentmatchplayer',
            name='game_wins',
            field=models.PositiveSmallIntegerField(default=0, help_text='Games won within this best-of-N match.'),
        ),
    ]
