# Generated by Django 4.2.29 on 2026-04-18 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('phyrexian', '0012_add_best_of_and_game_wins'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('format', models.CharField(choices=[('standard', 'Standard'), ('pioneer', 'Pioneer'), ('modern', 'Modern'), ('legacy', 'Legacy'), ('vintage', 'Vintage'), ('commander', 'Commander'), ('pauper', 'Pauper'), ('draft', 'Draft'), ('sealed', 'Sealed'), ('oathbreaker', 'Oathbreaker'), ('brawl', 'Brawl'), ('other', 'Other')], max_length=20)),
                ('tournaments_played', models.PositiveIntegerField(default=0)),
                ('tournaments_won', models.PositiveIntegerField(default=0, help_text='1st place finishes.')),
                ('top_4', models.PositiveIntegerField(default=0)),
                ('match_wins', models.PositiveIntegerField(default=0)),
                ('match_losses', models.PositiveIntegerField(default=0)),
                ('match_draws', models.PositiveIntegerField(default=0)),
                ('game_wins', models.PositiveIntegerField(default=0)),
                ('game_losses', models.PositiveIntegerField(default=0)),
                ('best_placement', models.PositiveSmallIntegerField(default=0, help_text='Best tournament finish (1 = won). 0 = never finished.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tournament stats',
                'verbose_name_plural': 'tournament stats',
                'ordering': ['-tournaments_won', '-match_wins'],
            },
        ),
        migrations.AddConstraint(
            model_name='tournamentstats',
            constraint=models.UniqueConstraint(fields=('user', 'format'), name='unique_user_format_tstats'),
        ),
    ]
