# Generated by Django 4.2.29 on 2026-03-24 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('multiverse', '0004_alter_cardprint_set_type_alter_cardset_set_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('collection_type', models.CharField(choices=[('binder', 'Binder'), ('wishlist', 'Wishlist'), ('tradelist', 'Trade List'), ('loanlist', 'Loan List')], default='binder', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('cover_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='multiverse.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'collection',
                'verbose_name_plural': 'collections',
                'ordering': ['collection_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('format', models.CharField(choices=[('standard', 'Standard'), ('pioneer', 'Pioneer'), ('modern', 'Modern'), ('legacy', 'Legacy'), ('vintage', 'Vintage'), ('commander', 'Commander'), ('pauper', 'Pauper'), ('draft', 'Draft'), ('sealed', 'Sealed'), ('oathbreaker', 'Oathbreaker'), ('brawl', 'Brawl'), ('other', 'Other')], default='commander', max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('cover_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='multiverse.card')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'deck',
                'verbose_name_plural': 'decks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('zone', models.CharField(choices=[('main', 'Maindeck'), ('sideboard', 'Sideboard'), ('commander', 'Commander'), ('companion', 'Companion'), ('maybeboard', 'Maybeboard'), ('reserve', 'Reserve'), ('extras', 'Tokens & More')], default='main', max_length=15)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('owned', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_entries', to='multiverse.card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='tolarian.deck')),
                ('print', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deck_entries', to='multiverse.cardprint')),
            ],
            options={
                'verbose_name': 'deck card',
                'verbose_name_plural': 'deck cards',
                'ordering': ['zone', 'card__name'],
            },
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('condition', models.CharField(choices=[('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Damaged')], default='NM', max_length=5)),
                ('finish', models.CharField(choices=[('nonfoil', 'Non-Foil'), ('foil', 'Foil'), ('premodern', 'Pre-Modern Foil'), ('ampersand', 'Ampersand Foil'), ('confetti', 'Confetti Foil'), ('doublerainbow', 'Double-Rainbow Foil'), ('firstplace', 'First Place Foil'), ('fractur', 'Fractur Foil'), ('etched', 'Etched'), ('galaxy', 'Galaxy Foil'), ('gilded', 'Gilded Foil'), ('glossy', 'Glossy'), ('halo', 'Halo Foil'), ('invisible', 'Invisible Ink Foil'), ('mana', 'Mana Foil'), ('neonink', 'Neon Ink Foil'), ('oilslick', 'Oil Slick Raised Foil'), ('ripple', 'Ripple Foil'), ('silverscreen', 'Silver Screen Foil'), ('stepcomplete', 'Step & Complete Foil'), ('surge', 'Surge Foil'), ('textured', 'Textured Foil'), ('vault', 'From the Vault Foil')], default='nonfoil', max_length=15)),
                ('language', models.CharField(default='en', max_length=10)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio de compra (USD)')),
                ('notes', models.TextField(blank=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_items', to='multiverse.card')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tolarian.collection')),
                ('print', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_items', to='multiverse.cardprint')),
            ],
            options={
                'verbose_name': 'collection item',
                'verbose_name_plural': 'collection items',
                'ordering': ['card__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='deckcard',
            constraint=models.UniqueConstraint(fields=('deck', 'card', 'zone'), name='unique_deck_card_zone'),
        ),
        migrations.AddConstraint(
            model_name='collectionitem',
            constraint=models.UniqueConstraint(fields=('collection', 'card', 'print', 'condition', 'finish', 'language'), name='unique_collection_item'),
        ),
    ]
