# Generated by Django 4.2.29 on 2026-03-29 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tolarian', '0002_change_cover_card_to_cardprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='loan_to_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prestado a (nombre)'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='loan_to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaned_items', to=settings.AUTH_USER_MODEL, verbose_name='Prestado a (usuario)'),
        ),
    ]
