# Generated by Django 4.2.29 on 2026-03-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolarian', '0003_add_loan_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deckcard',
            name='unique_deck_card_zone',
        ),
        migrations.AddConstraint(
            model_name='deckcard',
            constraint=models.UniqueConstraint(fields=('deck', 'card', 'zone', 'print'), name='unique_deck_card_zone_print'),
        ),
    ]
