# Generated by Django 4.2.29 on 2026-03-30 00:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tolarian', '0004_update_deck_card_unique_constraint_include_print'),
    ]

    operations = [
        migrations.AddField(
            model_name='deckcard',
            name='is_game_changer',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DeckCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deck_categories', to='tolarian.deck')),
            ],
            options={
                'verbose_name': 'deck category',
                'verbose_name_plural': 'deck categories',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.AddField(
            model_name='deckcard',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='tolarian.deckcategory'),
        ),
        migrations.AddConstraint(
            model_name='deckcategory',
            constraint=models.UniqueConstraint(fields=('deck', 'name'), name='unique_deck_category_name'),
        ),
    ]
