# Generated by Django 4.2.29 on 2026-03-31 04:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tolarian', '0006_convert_category_fk_to_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='share_token',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='DeckVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('snapshot', models.JSONField()),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='tolarian.deck')),
            ],
            options={
                'verbose_name': 'deck version',
                'verbose_name_plural': 'deck versions',
                'ordering': ['-version'],
            },
        ),
        migrations.AddConstraint(
            model_name='deckversion',
            constraint=models.UniqueConstraint(fields=('deck', 'version'), name='unique_deck_version_number'),
        ),
    ]
