# Generated by Django 4.2.29 on 2026-04-19 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('omenpath', '0001_initial'),
        ('tolarian', '0007_deck_share_token_deckversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionitem',
            name='acquired_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards_given', to=settings.AUTH_USER_MODEL, verbose_name='Adquirida de (usuario)'),
        ),
        migrations.AddField(
            model_name='collectionitem',
            name='acquired_via',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acquired_items', to='omenpath.transaction'),
        ),
    ]
