# Generated by Django 4.2.29 on 2026-03-20 14:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('multiverse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='creature_types',
            field=models.ManyToManyField(blank=True, related_name='cards', to='core.creaturetype'),
        ),
        migrations.AlterField(
            model_name='card',
            name='layout',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('split', 'Split'), ('flip', 'Flip'), ('transform', 'Transform'), ('modal_dfc', 'Modal DFC'), ('meld', 'Meld'), ('leveler', 'Leveler'), ('class', 'Class'), ('case', 'Case'), ('saga', 'Saga'), ('adventure', 'Adventure'), ('planar', 'Planar'), ('scheme', 'Scheme'), ('vanguard', 'Vanguard'), ('token', 'Token'), ('double_faced_token', 'Double Faced Token'), ('emblem', 'Emblem'), ('augment', 'Augment'), ('host', 'Host'), ('art_series', 'Art Series'), ('reversible_card', 'Reversible Card'), ('battle', 'Battle'), ('attraction', 'Attraction')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cardprint',
            name='border_color',
            field=models.CharField(blank=True, choices=[('black', 'Black'), ('white', 'White'), ('silver', 'Silver'), ('gold', 'Gold'), ('borderless', 'Borderless')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cardprint',
            name='rarity',
            field=models.CharField(blank=True, choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('mythic', 'Mythic Rare'), ('special', 'Special'), ('bonus', 'Bonus'), ('timeshifted', 'Timeshifted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cardprint',
            name='set_type',
            field=models.CharField(blank=True, choices=[('core', 'Core Set'), ('expansion', 'Expansion'), ('masters', 'Masters'), ('alchemy', 'Alchemy'), ('masterpiece', 'Masterpiece'), ('arsenal', 'Arsenal'), ('from_the_vault', 'From the Vault'), ('spellbook', 'Spellbook'), ('premium_deck', 'Premium Deck'), ('duel_deck', 'Duel Deck'), ('draft_innovation', 'Draft Innovation'), ('treasure_chest', 'Treasure Chest'), ('commander', 'Commander'), ('planechase', 'Planechase'), ('archenemy', 'Archenemy'), ('vanguard', 'Vanguard'), ('un_set', 'Un-Set'), ('funny', 'Funny'), ('starter', 'Starter'), ('jumpstart', 'Jumpstart'), ('box', 'Box'), ('promo', 'Promo'), ('token', 'Token'), ('memorabilia', 'Memorabilia'), ('minigame', 'Minigame'), ('eternal', 'Eternal'), ('heroes_of_the_realm', 'Heroes of the Realm'), ('front_cards', 'Jumpstart Front Cards'), ('planar_deck', 'Planar Deck'), ('schemes_deck', 'Scheme Deck'), ('scene_box', 'Scene Box'), ('championship_deck', 'Championship Deck')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='set_type',
            field=models.CharField(blank=True, choices=[('core', 'Core Set'), ('expansion', 'Expansion'), ('masters', 'Masters'), ('alchemy', 'Alchemy'), ('masterpiece', 'Masterpiece'), ('arsenal', 'Arsenal'), ('from_the_vault', 'From the Vault'), ('spellbook', 'Spellbook'), ('premium_deck', 'Premium Deck'), ('duel_deck', 'Duel Deck'), ('draft_innovation', 'Draft Innovation'), ('treasure_chest', 'Treasure Chest'), ('commander', 'Commander'), ('planechase', 'Planechase'), ('archenemy', 'Archenemy'), ('vanguard', 'Vanguard'), ('un_set', 'Un-Set'), ('funny', 'Funny'), ('starter', 'Starter'), ('jumpstart', 'Jumpstart'), ('box', 'Box'), ('promo', 'Promo'), ('token', 'Token'), ('memorabilia', 'Memorabilia'), ('minigame', 'Minigame'), ('eternal', 'Eternal'), ('heroes_of_the_realm', 'Heroes of the Realm'), ('front_cards', 'Jumpstart Front Cards'), ('planar_deck', 'Planar Deck'), ('schemes_deck', 'Scheme Deck'), ('scene_box', 'Scene Box'), ('championship_deck', 'Championship Deck')], max_length=50),
        ),
        migrations.CreateModel(
            name='CardFace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('face_index', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=250)),
                ('printed_name', models.CharField(blank=True, max_length=250)),
                ('type_line', models.CharField(blank=True, max_length=250)),
                ('printed_type_line', models.CharField(blank=True, max_length=250)),
                ('oracle_text', models.TextField(blank=True)),
                ('printed_text', models.TextField(blank=True)),
                ('mana_cost', models.CharField(blank=True, max_length=100)),
                ('cmc', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('colors', models.JSONField(default=list)),
                ('color_indicator', models.JSONField(default=list)),
                ('power', models.CharField(blank=True, max_length=10)),
                ('toughness', models.CharField(blank=True, max_length=10)),
                ('loyalty', models.CharField(blank=True, max_length=10)),
                ('defense', models.CharField(blank=True, max_length=10)),
                ('artist', models.CharField(blank=True, max_length=200)),
                ('artist_id', models.UUIDField(blank=True, null=True)),
                ('illustration_id', models.UUIDField(blank=True, null=True)),
                ('image_uris', models.JSONField(default=dict)),
                ('flavor_text', models.TextField(blank=True)),
                ('flavor_name', models.CharField(blank=True, max_length=250)),
                ('watermark', models.CharField(blank=True, max_length=50)),
                ('layout', models.CharField(blank=True, max_length=50)),
                ('oracle_id', models.UUIDField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='multiverse.card')),
            ],
            options={
                'verbose_name': 'card face',
                'verbose_name_plural': 'card faces',
                'ordering': ['card', 'face_index'],
            },
        ),
    ]
