# Generated by Django 4.2.29 on 2026-03-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0002_card_creature_types_alter_card_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='is_standard_legal',
            field=models.BooleanField(default=False),
        ),
    ]
