# Generated by Django 4.2.29 on 2026-03-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0003_cardset_is_standard_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprint',
            name='set_type',
            field=models.CharField(blank=True, choices=[('core', 'Core Set'), ('expansion', 'Expansion'), ('masters', 'Masters'), ('alchemy', 'Alchemy'), ('masterpiece', 'Masterpiece'), ('arsenal', 'Arsenal'), ('from_the_vault', 'From the Vault'), ('spellbook', 'Spellbook'), ('premium_deck', 'Premium Deck'), ('duel_deck', 'Duel Deck'), ('draft_innovation', 'Draft Innovation'), ('treasure_chest', 'Treasure Chest'), ('commander', 'Commander'), ('planechase', 'Planechase'), ('archenemy', 'Archenemy'), ('vanguard', 'Vanguard'), ('un_set', 'Un-Set'), ('funny', 'Funny'), ('starter', 'Starter'), ('jumpstart', 'Jumpstart'), ('box', 'Box'), ('promo', 'Promo'), ('token', 'Token'), ('memorabilia', 'Memorabilia'), ('minigame', 'Minigame'), ('eternal', 'Eternal'), ('heroes_of_the_realm', 'Heroes of the Realm'), ('front_cards', 'Jumpstart Front Cards'), ('planar_deck', 'Planar Deck'), ('schemes_deck', 'Scheme Deck'), ('scene_box', 'Scene Box'), ('championship_deck', 'Championship Deck'), ('art_series', 'Art Series')], max_length=50),
        ),
        migrations.AlterField(
            model_name='cardset',
            name='set_type',
            field=models.CharField(blank=True, choices=[('core', 'Core Set'), ('expansion', 'Expansion'), ('masters', 'Masters'), ('alchemy', 'Alchemy'), ('masterpiece', 'Masterpiece'), ('arsenal', 'Arsenal'), ('from_the_vault', 'From the Vault'), ('spellbook', 'Spellbook'), ('premium_deck', 'Premium Deck'), ('duel_deck', 'Duel Deck'), ('draft_innovation', 'Draft Innovation'), ('treasure_chest', 'Treasure Chest'), ('commander', 'Commander'), ('planechase', 'Planechase'), ('archenemy', 'Archenemy'), ('vanguard', 'Vanguard'), ('un_set', 'Un-Set'), ('funny', 'Funny'), ('starter', 'Starter'), ('jumpstart', 'Jumpstart'), ('box', 'Box'), ('promo', 'Promo'), ('token', 'Token'), ('memorabilia', 'Memorabilia'), ('minigame', 'Minigame'), ('eternal', 'Eternal'), ('heroes_of_the_realm', 'Heroes of the Realm'), ('front_cards', 'Jumpstart Front Cards'), ('planar_deck', 'Planar Deck'), ('schemes_deck', 'Scheme Deck'), ('scene_box', 'Scene Box'), ('championship_deck', 'Championship Deck'), ('art_series', 'Art Series')], max_length=50),
        ),
    ]
