# Generated by Django 4.2.29 on 2026-03-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0004_alter_cardprint_set_type_alter_cardset_set_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardset',
            name='is_universe_beyond',
            field=models.BooleanField(default=False),
        ),
    ]
