# Generated by Django 4.2.29 on 2026-04-11 16:42

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0005_cardset_is_universe_beyond'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardprint',
            options={'ordering': ['-cardset__released_at', django.db.models.functions.text.Length('collector_number'), 'collector_number'], 'verbose_name': 'card print', 'verbose_name_plural': 'card prints'},
        ),
    ]
