# Generated by Django 4.2.29 on 2026-04-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiverse', '0006_natural_collector_number_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardprint',
            name='frame_effects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='cardprint',
            name='preview',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='cardprint',
            name='promo_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
