# Generated by Django 4.2.29 on 2026-04-19 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('multiverse', '0007_alter_cardprint_frame_effects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('listing_type', models.CharField(choices=[('sell', 'For sale'), ('buy_wanted', 'Wanted to buy')], default='sell', max_length=15)),
                ('condition', models.CharField(choices=[('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Damaged')], default='NM', max_length=5)),
                ('finish', models.CharField(choices=[('nonfoil', 'Non-Foil'), ('foil', 'Foil'), ('premodern', 'Pre-Modern Foil'), ('ampersand', 'Ampersand Foil'), ('confetti', 'Confetti Foil'), ('doublerainbow', 'Double-Rainbow Foil'), ('firstplace', 'First Place Foil'), ('fractur', 'Fractur Foil'), ('etched', 'Etched'), ('galaxy', 'Galaxy Foil'), ('gilded', 'Gilded Foil'), ('glossy', 'Glossy'), ('halo', 'Halo Foil'), ('invisible', 'Invisible Ink Foil'), ('mana', 'Mana Foil'), ('neonink', 'Neon Ink Foil'), ('oilslick', 'Oil Slick Raised Foil'), ('ripple', 'Ripple Foil'), ('silverscreen', 'Silver Screen Foil'), ('stepcomplete', 'Step & Complete Foil'), ('surge', 'Surge Foil'), ('textured', 'Textured Foil'), ('vault', 'From the Vault Foil')], default='nonfoil', max_length=15)),
                ('language', models.CharField(default='en', max_length=10)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('asking_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('friends', 'Friends only')], default='public', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('completed', 'Completed')], default='open', max_length=15)),
                ('card_print', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='multiverse.cardprint')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'listing',
                'verbose_name_plural': 'listings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('kind', models.CharField(choices=[('trade', 'Trade'), ('sale', 'Sale')], max_length=10)),
                ('price_agreed', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='proposed', max_length=15)),
                ('confirmed_by_a', models.BooleanField(default=False)),
                ('confirmed_by_b', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='omenpath.listing')),
                ('party_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_initiated', to=settings.AUTH_USER_MODEL)),
                ('party_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('side', models.CharField(choices=[('from_a', 'From initiator'), ('from_b', 'From recipient')], max_length=10)),
                ('condition', models.CharField(choices=[('NM', 'Near Mint'), ('LP', 'Lightly Played'), ('MP', 'Moderately Played'), ('HP', 'Heavily Played'), ('DMG', 'Damaged')], default='NM', max_length=5)),
                ('finish', models.CharField(choices=[('nonfoil', 'Non-Foil'), ('foil', 'Foil'), ('premodern', 'Pre-Modern Foil'), ('ampersand', 'Ampersand Foil'), ('confetti', 'Confetti Foil'), ('doublerainbow', 'Double-Rainbow Foil'), ('firstplace', 'First Place Foil'), ('fractur', 'Fractur Foil'), ('etched', 'Etched'), ('galaxy', 'Galaxy Foil'), ('gilded', 'Gilded Foil'), ('glossy', 'Glossy'), ('halo', 'Halo Foil'), ('invisible', 'Invisible Ink Foil'), ('mana', 'Mana Foil'), ('neonink', 'Neon Ink Foil'), ('oilslick', 'Oil Slick Raised Foil'), ('ripple', 'Ripple Foil'), ('silverscreen', 'Silver Screen Foil'), ('stepcomplete', 'Step & Complete Foil'), ('surge', 'Surge Foil'), ('textured', 'Textured Foil'), ('vault', 'From the Vault Foil')], default='nonfoil', max_length=15)),
                ('language', models.CharField(default='en', max_length=10)),
                ('quantity', models.PositiveSmallIntegerField(default=1)),
                ('unit_value', models.DecimalField(blank=True, decimal_places=2, help_text='Snapshot of market value at proposal time (USD).', max_digits=10, null=True)),
                ('card_print', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='multiverse.cardprint')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='omenpath.transaction')),
            ],
            options={
                'verbose_name': 'transaction item',
                'verbose_name_plural': 'transaction items',
                'ordering': ['side', 'card_print__card__name'],
            },
        ),
        migrations.CreateModel(
            name='PriceQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('scryfall', 'Scryfall'), ('tcgplayer', 'TCGPlayer'), ('cardmarket', 'Cardmarket'), ('user', 'User-set')], max_length=15)),
                ('finish', models.CharField(choices=[('nonfoil', 'Non-Foil'), ('foil', 'Foil'), ('premodern', 'Pre-Modern Foil'), ('ampersand', 'Ampersand Foil'), ('confetti', 'Confetti Foil'), ('doublerainbow', 'Double-Rainbow Foil'), ('firstplace', 'First Place Foil'), ('fractur', 'Fractur Foil'), ('etched', 'Etched'), ('galaxy', 'Galaxy Foil'), ('gilded', 'Gilded Foil'), ('glossy', 'Glossy'), ('halo', 'Halo Foil'), ('invisible', 'Invisible Ink Foil'), ('mana', 'Mana Foil'), ('neonink', 'Neon Ink Foil'), ('oilslick', 'Oil Slick Raised Foil'), ('ripple', 'Ripple Foil'), ('silverscreen', 'Silver Screen Foil'), ('stepcomplete', 'Step & Complete Foil'), ('surge', 'Surge Foil'), ('textured', 'Textured Foil'), ('vault', 'From the Vault Foil')], default='nonfoil', max_length=15)),
                ('currency', models.CharField(default='USD', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('card_print', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_quotes', to='multiverse.cardprint')),
            ],
            options={
                'verbose_name': 'price quote',
                'verbose_name_plural': 'price quotes',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'kind'], name='omenpath_tr_status_961a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['party_a', 'status'], name='omenpath_tr_party_a_ed358f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['party_b', 'status'], name='omenpath_tr_party_b_b0e2a9_idx'),
        ),
        migrations.AddIndex(
            model_name='pricequote',
            index=models.Index(fields=['card_print', 'source', 'finish'], name='omenpath_pr_card_pr_a90a1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricequote',
            constraint=models.UniqueConstraint(fields=('card_print', 'source', 'finish', 'currency'), name='unique_price_quote'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'listing_type'], name='omenpath_li_status_caf066_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['visibility', 'status'], name='omenpath_li_visibil_fa49c2_idx'),
        ),
    ]
