# Generated by Django 4.2.29 on 2026-05-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omenpath', '0002_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Auto-close moment. Null means it never expires.', null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('expired', 'Expired'), ('closed', 'Closed'), ('completed', 'Completed')], default='open', max_length=15),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'expires_at'], name='omenpath_li_status_176089_idx'),
        ),
    ]
