# Generated by Django 4.2.29 on 2026-05-02 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('omenpath', '0003_listing_expires_at_alter_listing_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('event_type', models.CharField(choices=[('proposed', 'Proposed'), ('countered', 'Countered'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed'), ('unconfirmed', 'Unconfirmed'), ('completed', 'Completed')], max_length=15)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='omenpath_events', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='omenpath.transaction')),
            ],
            options={
                'verbose_name': 'transaction event',
                'verbose_name_plural': 'transaction events',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['transaction', 'created_at'], name='omenpath_tr_transac_25def4_idx')],
            },
        ),
    ]
