# Generated by Django 4.2.29 on 2026-05-02 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('omenpath', '0004_transactionevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='omenpath_messages', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='omenpath.transaction')),
            ],
            options={
                'verbose_name': 'transaction message',
                'verbose_name_plural': 'transaction messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['transaction', 'created_at'], name='omenpath_tr_transac_ccd1fc_idx')],
            },
        ),
    ]
