# Generated by Django 4.2.29 on 2026-03-20 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_format',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('pioneer', 'Pioneer'), ('modern', 'Modern'), ('legacy', 'Legacy'), ('vintage', 'Vintage'), ('commander', 'Commander'), ('pauper', 'Pauper'), ('draft', 'Draft'), ('sealed', 'Sealed')], max_length=20, verbose_name='Preferred Format'),
        ),
    ]
